name: Secure CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-scan-push:
    name: Build Scan Push Validate
    runs-on: self-hosted

    env:
      IMAGE_NAME: secure-app
      REGISTRY: 192.168.56.100:5000
      APP_PATH: /home/charlie/secure-by-design-distributed-cloud-lab-architecture/docker/secure-app

    steps:
      - name: Check Docker
        run: |
          docker version
          docker ps

      - name: Build Image
        run: |
          docker build -t secure-app:${{ github.sha }} /home/charlie/secure-by-design-distributed-cloud-lab-architecture/docker/secure-app

      - name: Scan Image With Trivy
        run: |
          trivy image --severity HIGH,CRITICAL --exit-code 1 secure-app:${{ github.sha }}

      - name: Tag Image
        run: |
          docker tag secure-app:${{ github.sha }} 192.168.56.100:5000/secure-app:${{ github.sha }}
          docker tag secure-app:${{ github.sha }} 192.168.56.100:5000/secure-app:latest

      - name: Push Image
        run: |
          docker push 192.168.56.100:5000/secure-app:${{ github.sha }}
          docker push 192.168.56.100:5000/secure-app:latest

      - name: Validate Registry
        run: |
          curl -k https://192.168.56.100:5000/v2/_catalog
EOF
