name: Secure CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-scan-push:
    runs-on: [self-hosted, Linux, X64, docker]

    steps:
      - name: Check Docker
        run: |
          docker ps
          docker version

      - name: Build Image
        run: |
          docker build -t secure-app:v1 /home/charlie/secure-by-design-distributed-cloud-lab-architecture/docker/secure-app

      - name: Tag Image
        run: |
          docker tag secure-app:v1 192.168.56.100:5000/secure-app:v1

      - name: Push Image to Private Registry
        run: |
          docker push 192.168.56.100:5000/secure-app:v1

      - name: Validate Registry Push
        run: |
          curl -k https://192.168.56.100:5000/v2/_catalog
