name: Secure CI/CD Pipeline

on:
  push:
    branches: ["main"]

jobs:
  build-push:
    runs-on: self-hosted

    steps:
      - name: Build Docker Image
        run: |
          cd docker/secure-app
          docker built -t secure-appv1 .

      - name: Tag Image
        run: |
          docker tag secure-app:v1 192.168.56.100:5000/secure-app:v1
      - name: Push to Private Registry
        run: |
          docker push 192.168.56.100:5000/secure-app:v1
